// Code generated by hertz generator.

package apis

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/evaluation/optimize/optimizeservice"
)

var localOptimizeSvc optimizeservice.Client

// CreateOptimizeTask .
// @router /api/evaluation/v1/prompts/:prompt_id/optimize_tasks [POST]
func CreateOptimizeTask(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localOptimizeSvc.CreateOptimizeTask)
}

// ListOptimizeTasks .
// @router /api/evaluation/v1/prompts/:prompt_id/optimize_tasks/list [POST]
func ListOptimizeTasks(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localOptimizeSvc.ListOptimizeTasks)
}

// GetOptimizeTask .
// @router /api/evaluation/v1/optimize_tasks/:task_id [GET]
func GetOptimizeTask(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localOptimizeSvc.GetOptimizeTask)
}

// CancelOptimizeTask .
// @router /api/evaluation/v1/optimize_tasks/:task_id/cancel [POST]
func CancelOptimizeTask(ctx context.Context, c *app.RequestContext) {
	invokeAndRender(ctx, c, localOptimizeSvc.CancelOptimizeTask)
}
