// Code generated by Kitex v0.13.1. DO NOT EDIT.

package optimizeservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	optimize "github.com/coze-dev/coze-loop/backend/kitex_gen/coze/loop/evaluation/optimize"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateOptimizeTask(ctx context.Context, req *optimize.CreateOptimizeTaskRequest, callOptions ...callopt.Option) (r *optimize.CreateOptimizeTaskResponse, err error)
	ListOptimizeTasks(ctx context.Context, req *optimize.ListOptimizeTasksRequest, callOptions ...callopt.Option) (r *optimize.ListOptimizeTasksResponse, err error)
	GetOptimizeTask(ctx context.Context, req *optimize.GetOptimizeTaskRequest, callOptions ...callopt.Option) (r *optimize.GetOptimizeTaskResponse, err error)
	CancelOptimizeTask(ctx context.Context, req *optimize.CancelOptimizeTaskRequest, callOptions ...callopt.Option) (r *optimize.CancelOptimizeTaskResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kOptimizeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kOptimizeServiceClient struct {
	*kClient
}

func (p *kOptimizeServiceClient) CreateOptimizeTask(ctx context.Context, req *optimize.CreateOptimizeTaskRequest, callOptions ...callopt.Option) (r *optimize.CreateOptimizeTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateOptimizeTask(ctx, req)
}

func (p *kOptimizeServiceClient) ListOptimizeTasks(ctx context.Context, req *optimize.ListOptimizeTasksRequest, callOptions ...callopt.Option) (r *optimize.ListOptimizeTasksResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListOptimizeTasks(ctx, req)
}

func (p *kOptimizeServiceClient) GetOptimizeTask(ctx context.Context, req *optimize.GetOptimizeTaskRequest, callOptions ...callopt.Option) (r *optimize.GetOptimizeTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetOptimizeTask(ctx, req)
}

func (p *kOptimizeServiceClient) CancelOptimizeTask(ctx context.Context, req *optimize.CancelOptimizeTaskRequest, callOptions ...callopt.Option) (r *optimize.CancelOptimizeTaskResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CancelOptimizeTask(ctx, req)
}
