CREATE TABLE IF NOT EXISTS `optimize_task` (
  `id` bigint unsigned NOT NULL COMMENT 'Optimize task ID',
  `workspace_id` bigint unsigned NOT NULL COMMENT 'Workspace ID',
  `prompt_id` bigint unsigned NOT NULL COMMENT 'Prompt ID',
  `prompt_version` varchar(128) NOT NULL DEFAULT '' COMMENT 'Baseline prompt version',
  `name` varchar(128) NOT NULL DEFAULT '' COMMENT 'Task name',
  `source_type` varchar(32) NOT NULL COMMENT 'experiment or eval_set',
  `source_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT 'Experiment or evaluation set version ID',
  `case_item_ids` json NOT NULL COMMENT 'Selected case IDs',
  `mapping` json NOT NULL COMMENT 'Field mapping snapshot',
  `baseline_prompt` json NOT NULL COMMENT 'Immutable baseline prompt snapshot',
  `optimizer_model_id` bigint unsigned NOT NULL COMMENT 'Optimizer and judge model ID',
  `mode_score` decimal(6,5) NOT NULL DEFAULT 0.50000 COMMENT 'Cost-quality tradeoff',
  `status` varchar(32) NOT NULL DEFAULT 'queued' COMMENT 'Task status',
  `progress` int unsigned NOT NULL DEFAULT 0 COMMENT 'Progress from 0 to 100',
  `result` json DEFAULT NULL COMMENT 'Optimization report',
  `error_msg` varchar(2048) NOT NULL DEFAULT '' COMMENT 'Last error',
  `cancel_requested` tinyint unsigned NOT NULL DEFAULT 0 COMMENT 'Cancellation flag',
  `lease_token` varchar(64) NOT NULL DEFAULT '' COMMENT 'Current worker lease token',
  `lease_expires_at` timestamp(3) NULL DEFAULT NULL COMMENT 'Current worker lease expiry',
  `attempt_count` int unsigned NOT NULL DEFAULT 0 COMMENT 'Worker claim attempts',
  `created_by` varchar(128) NOT NULL DEFAULT '' COMMENT 'Creator',
  `created_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `idx_workspace_prompt_created` (`workspace_id`, `prompt_id`, `created_at`),
  KEY `idx_status_updated` (`status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Prompt intelligent optimization task';
